### ISSUE TITLE
Missing Tags

### ISSUE THREAD

**Issue by vmwxiong** [gsdriver/ssml-check-core#11]
The following valid Amazon SSML tags are currently treated as rejections:

- `mark`
- `amazon:breath`
- `amazon:auto-breaths`
- `<prosody amazon:max-duration="2s">`

**Comment by vmwxiong** [comment]
https://docs.aws.amazon.com/polly/latest/dg/supportedtags.html

**Comment by gsdriver** [comment]
Thanks for pointing these out - I just added support for these tags
