### ISSUE TITLE
Google added support for a lot of new tags and features

### ISSUE THREAD

**Issue by lenaschimmel** [gsdriver/ssml-check-core#12]
During 2021, Google introduces some new features:
 * `<phoneme>`: Customize the pronunciation of specific words.
 * ~~`<say-as interpret-as="duration">`: Specify durations.~~
 * `<voice>`: Switch between voices in the same request.
 * `<lang>`: Use multiple languages in the same request.
 * ~~`<mark>`: Return the timepoint of a specified point in your transcript.~~

_(it seems that ssml-check-core  already supports `<say-as interpret-as="duration">` and `<mark>` just fine)_

**The solution I'd like:**
ssml-check-core should probably support them in the same way the well-established tags are supported.

**Describe alternatives you've considered**
If some or all of those features are not supported, the documentation should state this.

**Additional context**
At first, those features were in beta phase (see [this archived page](https://web.archive.org/web/20210524075559/https://cloud.google.com/text-to-speech/docs/ssml-beta)) but I think they are out of beta now. I'm unsure if/how this relates to Google's `v1` and `v1beta1` APIs.

From my (limited) experience, the `<phoneme>` implementation is very picky and hard to debug, since every locale only supports a subset of the IPA phones, and the `<phoneme>` tag is completely ignored as soon as there's just one unsupported character in the `ph` attribute. The validation of `ph` would be a very useful feature, but also very complex. Maybe this should be a separate issue, or even be outsourced to a separate library?

**Comment by var1ap** [comment]
@gsdriver, can you please take a look?

**Comment by gsdriver** [comment]
Created a new issue for the ph attribute verification. The other items noted (supporting phoneme, voice, and lang) have been added into version 0.3.8
