### ISSUE TITLE
Missing Amazon role attribute values

### ISSUE THREAD

**Issue by bayloun** [gsdriver/ssml-check-core#13]
The following valid Amazon SSML tags are currently treated as rejections:

role="amazon:DT"
role="amazon:IN"
role="amazon:JJ"

https://docs.aws.amazon.com/polly/latest/dg/supportedtags.html#w-tag

ssml-check-core currently only has support for VB, VBD, NN, SENSE_1: https://github.com/gsdriver/ssml-check-core/blob/master/checktag.js#L726

**Comment by bayloun** [comment]
Went ahead and made a pull request for this: https://github.com/gsdriver/ssml-check-core/pull/14

**Comment by gsdriver** [comment]
Thanks - approved and published a new version v0.3.4 with this change
