### ISSUE TITLE
Some locales are missing from Amazon/Alexa "lang" tag

### ISSUE THREAD

**Issue by kurtisca** [gsdriver/ssml-check-core#16]
**Describe the bug**
Alexa SSML supports 15 different locales for the `xml:lang` attribute of the `lang` tag, 5 of which are missing.

**To Reproduce**
```
<speak>
  <lang xml:lang="es-MX">Hello</lang>
</speak>
```

**Expected behavior**
This should be valid SSML. See [Alexa Documentation](https://developer.amazon.com/en-US/docs/alexa/custom-skills/speech-synthesis-markup-language-ssml-reference.html#supported-locales-for-the-xmllang-attribute).

**Environment (please complete the following information):**
 - Platform: Alexa
 - Version Unknown

**Additional context**
I've already created a PR [here](https://github.com/gsdriver/ssml-check-core/pull/15) for the fix. It includes the 5 missing locales.

**Comment by gsdriver** [comment]
Good catch - thanks for the contribution!

**Comment by gsdriver** [comment]
Released in version 0.3.5
