### ISSUE TITLE
more little things..

### ISSUE THREAD

**Issue by janniksam** [gsdriver/ssml-check-core#4]
1. In my opinion this validation is wrong at the break's "time" attribute. I dont find it anywhere in the documentation. Google doc says:

time: Sets the length of the break by seconds or milliseconds (e.g. "3s" or "250ms").

```js
  } else if ((platform === 'google') && text.match(/^[0-9]+(\.[0-9]+)?$/g)) {
time = 1000 * parseInt(text);
```

Further more, where did you find that decimal places are allowed? Havent tried it yet, but couldnt find it in the docs of amazon / google, either.

2.  copy paste mistake, the commented line shouldn't be there:

```js
case 'prosody':
// Attribute must be time or strength
```

**Comment by gsdriver** [comment]
I ran across an [article with several examples](https://medium.com/google-developers/advanced-ssml-for-actions-on-google-5cea45d868c9) from a Google engineer.  If you look halfway down, under the section titled "Boo!" there is an example of SSML with a break time set to '0.5'.  I tried it out in the Google Action simulator and sure enough it works, inserting a half second pause. It doesn't play on Amazon.  So I included it in the SDK.

Good catch on the comment - I removed it there and from phoneme.  Checked into the develop branch; will push out with the next update.
